services:
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - INPUT_QUEUE=minor_transactions
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUE=transactions
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
  client_0:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
      - gateway
    environment:
    - INPUT_FILE=/datasets/HI-Small_Trans.csv
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    volumes:
    - ./datasets:/datasets
    - ./output:/output
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  projection_dispatcher:
    build:
      context: ./src/
      dockerfile: workers/worker/Dockerfile
    container_name: projection_dispatcher
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - OPERATION_TYPE=projection_dispatcher
      - INPUT_MIDDLEWARE_TYPE=queue
      - INPUT_QUEUE=transactions
      - OUTPUTS=minor_query
