services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  date_range_filter_r1_1:
    build:
      context: ./src/
      dockerfile: workers/worker/Dockerfile
    container_name: date_range_filter_r1_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - NODE_ID=3
      - RULE_ID=1
      - OPERATION_TYPE=date_range_filter
      - INPUT_MIDDLEWARE_TYPE=queue
      - INPUT_QUEUE=USD_transactions
      - OUTPUT_MIDDLEWARE_TYPE=queue
      - OUTPUTS=range_transactions
      - START_DATE=2022-09-01T00:15:00
      - END_DATE=2022-09-01T00:30:00
      - EOF_CONTROL_QUEUE=eof_control_queue_1
      
  amount_filter_r1_1:
    build:
      context: ./src/
      dockerfile: workers/worker/Dockerfile
    container_name: amount_filter_r1_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - NODE_ID=4
      - RULE_ID=1
      - OPERATION_TYPE=amount_filter
      - INPUT_MIDDLEWARE_TYPE=queue
      - INPUT_QUEUE=range_transactions
      - OUTPUT_MIDDLEWARE_TYPE=queue
      - OUTPUTS=minor_transactions
      - MINIMUM_AMOUNT=50
      - EOF_CONTROL_QUEUE=eof_control_queue_1

  coordinator:
    build:
      context: ./src/
      dockerfile: coordinator/base/Dockerfile
    container_name: coordinator
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      PYTHONPATH: /app
      RABBITMQ_HOST: rabbitmq
      COORDINATOR_QUEUE: coordinator_control_queue
      REPORT_RETRY_SECONDS: 5
      NODE_TIMEOUT_SECONDS: 9999
      MONITOR_INTERVAL_SECONDS: 9999
      STATE_DB_PATH: /app/data/state.db
      COORDINATOR_ID: 1
    volumes:
      - coordinator_data:/app/data
    restart: unless-stopped
  coordinator_2:
    build:
      context: ./src/
      dockerfile: coordinator/base/Dockerfile
    container_name: coordinator_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      PYTHONPATH: /app
      RABBITMQ_HOST: rabbitmq
      COORDINATOR_QUEUE: coordinator_control_queue
      REPORT_RETRY_SECONDS: 5
      NODE_TIMEOUT_SECONDS: 9999
      MONITOR_INTERVAL_SECONDS: 9999
      STATE_DB_PATH: /app/data/state.db
      COORDINATOR_ID: 2
    volumes:
      - coordinator_data:/app/data
    restart: unless-stopped

volumes:
  coordinator_data:
