services:
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    environment:
      - INPUT_QUEUE=minor_transactions
      - MOM_HOST=rabbitmq
      - OUTPUT_QUEUE=transactions
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=gateway
      - SERVER_PORT=5678
      - EOF_CONTROL_QUEUE=eof_control_queue_1
    networks:
      - money_laundering_net
  date_range_filter_r1_1:
    build:
      context: ./src/
      dockerfile: workers/worker/Dockerfile
    container_name: date_range_filter_r1_1
    environment:
      - RABBITMQ_HOST=rabbitmq
      - NODE_ID=3
      - RULE_ID=1
      - OPERATION_TYPE=date_range_filter
      - INPUT_MIDDLEWARE_TYPE=queue
      - INPUT_QUEUE=USD_transactions
      - OUTPUT_MIDDLEWARE_TYPE=queue
      - OUTPUTS=range_transactions
      - START_DATE=2022-09-01T00:15:00
      - END_DATE=2022-09-01T00:30:00
      - EOF_CONTROL_QUEUE=eof_control_queue_1
    networks:
      - money_laundering_net
      
  amount_filter_r1_1:
    build:
      context: ./src/
      dockerfile: workers/worker/Dockerfile
    container_name: amount_filter_r1_1
    environment:
      - RABBITMQ_HOST=rabbitmq
      - NODE_ID=4
      - RULE_ID=1
      - OPERATION_TYPE=amount_filter
      - INPUT_MIDDLEWARE_TYPE=queue
      - INPUT_QUEUE=range_transactions
      - OUTPUT_MIDDLEWARE_TYPE=queue
      - OUTPUTS=minor_transactions
      - MINIMUM_AMOUNT=50
      - EOF_CONTROL_QUEUE=eof_control_queue_1
    networks:
      - money_laundering_net

networks:
  money_laundering_net:
    external: true 

