SHELL := /bin/bash
PWD := $(shell pwd)

PYTHON := python3

VERIFY_DIR := src/tools/verification
DATA_DIR := test/data
OUTPUT_DIR := output
EXPECTED_DIR := src/tools/verification

INPUT_FILE ?= $(DATA_DIR)/INPUT_FILE.csv

# Expected outputs generated by verification scripts
RULE_1_EXPECTED ?= $(EXPECTED_DIR)/RULE_1_EXPECTED.csv
RULE_2_EXPECTED ?= $(EXPECTED_DIR)/RULE_2_EXPECTED.csv
RULE_3_EXPECTED ?= $(EXPECTED_DIR)/RULE_3_EXPECTED.csv
RULE_4_EXPECTED ?= $(EXPECTED_DIR)/RULE_4_EXPECTED.csv
RULE_5_EXPECTED ?= $(EXPECTED_DIR)/RULE_5_EXPECTED.csv

# Actual outputs generated by the TP
RULE_1_ACTUAL ?= $(OUTPUT_DIR)/RULE_1_OUTPUT.csv
RULE_2_ACTUAL ?= $(OUTPUT_DIR)/RULE_2_OUTPUT.csv
RULE_3_ACTUAL ?= $(OUTPUT_DIR)/RULE_3_OUTPUT.csv
RULE_4_ACTUAL ?= $(OUTPUT_DIR)/RULE_4_OUTPUT.csv
RULE_5_ACTUAL ?= $(OUTPUT_DIR)/RULE_5_OUTPUT.csv

up:
	mkdir -p output
	COMPOSE_HTTP_TIMEOUT=300 docker compose -f docker-compose.yaml up --build --remove-orphans --detach
	docker compose -f docker-compose.yaml logs --follow
.PHONY: up

down:
	docker compose -f docker-compose.yaml stop -t 5
	docker compose -f docker-compose.yaml down -v
	find output -mindepth 1 -delete
.PHONY: down

logs:
	docker compose -f docker-compose.yaml logs
.PHONY: logs

switch:
	@echo Escenarios de prueba:
	@echo "1) Regla 1 - Detección de transacciones menores a 50 USD"
	@echo "2) Regla 2 - Detección de máxima transacción por banco"
	@echo "3) Regla 3 - Detección de transacción menores al promedio cálculado"
	@echo "4) Regla 4 - Detección de patrón Scatter-Gather"
	@echo "5) Regla 5 - Cantidad de transacciones por vía de pago"
# 	@echo "6) Todas las reglas"
	@read -p "Selecciona uno [1-5]: " option;	\
	cp ./scenarios/$${option}.yaml docker-compose.yaml
.PHONY: switch

verify-help:
	@echo "Verification commands:"
	@echo ""
	@echo "Generate expected outputs:"
	@echo "  make expected-all"
	@echo "  make expected-rule-1"
	@echo "  make expected-rule-2"
	@echo "  make expected-rule-3"
	@echo "  make expected-rule-4"
	@echo "  make expected-rule-5"
	@echo ""
	@echo "Generate expected output and compare with actual output:"
	@echo "  make compare-all"
	@echo "  make compare-rule-1"
	@echo "  make compare-rule-2"
	@echo "  make compare-rule-3"
	@echo "  make compare-rule-4"
	@echo "  make compare-rule-5"
	@echo ""
	@echo "Aliases:"
	@echo "  make verify-all"
	@echo "  make verify-rule-1"
	@echo "  make verify-rule-2"
	@echo "  make verify-rule-3"
	@echo "  make verify-rule-4"
	@echo "  make verify-rule-5"
	@echo ""
	@echo "Examples:"
	@echo '  make expected-all INPUT_FILE="/path/to/HI-Medium_Trans.csv"'
	@echo '  make compare-rule-1 RULE_1_ACTUAL="output/minor_transactions.csv"'
.PHONY: verify-help

expected-all: expected-rule-1 expected-rule-2 expected-rule-3 expected-rule-4 expected-rule-5
.PHONY: expected-all

expected-rule-1:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_1.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_1_EXPECTED)"
.PHONY: expected-rule-1

expected-rule-2:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_2.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_2_EXPECTED)"
.PHONY: expected-rule-2

expected-rule-3:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_3.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_3_EXPECTED)"
.PHONY: expected-rule-3

expected-rule-4:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_4.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_4_EXPECTED)"
.PHONY: expected-rule-4

expected-rule-5:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_5.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_5_EXPECTED)"
.PHONY: expected-rule-5

compare-all: compare-rule-1 compare-rule-2 compare-rule-3 compare-rule-4 compare-rule-5
.PHONY: compare-all

compare-rule-1:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_1.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_1_EXPECTED)" \
		--actual-file "$(RULE_1_ACTUAL)"
.PHONY: compare-rule-1

compare-rule-2:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_2.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_2_EXPECTED)" \
		--actual-file "$(RULE_2_ACTUAL)"
.PHONY: compare-rule-2

compare-rule-3:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_3.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_3_EXPECTED)" \
		--actual-file "$(RULE_3_ACTUAL)"
.PHONY: compare-rule-3

compare-rule-4:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_4.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_4_EXPECTED)" \
		--actual-file "$(RULE_4_ACTUAL)"
.PHONY: compare-rule-4

compare-rule-5:
	$(PYTHON) $(VERIFY_DIR)/verify_rule_5.py \
		--input-file "$(INPUT_FILE)" \
		--expected-file "$(RULE_5_EXPECTED)" \
		--actual-file "$(RULE_5_ACTUAL)"
.PHONY: compare-rule-5

verify-all: compare-all
.PHONY: verify-all

verify-rule-1: compare-rule-1
.PHONY: verify-rule-1

verify-rule-2: compare-rule-2
.PHONY: verify-rule-2

verify-rule-3: compare-rule-3
.PHONY: verify-rule-3

verify-rule-4: compare-rule-4
.PHONY: verify-rule-4

verify-rule-5: compare-rule-5
.PHONY: verify-rule-5