queries:
  query_2:
    pipeline:
      - name: projection_dispatcher
        instances: 2
        stateful: false
        eof_queue: eof_projection_dispatcher_q2
        ready_queue: ready_projection_dispatcher_q2

      - name: currency_filter_q2
        instances: 3
        stateful: false
        eof_queue: eof_currency_filter_q2
        ready_queue: ready_currency_filter_q2

      - name: local_bank_max_aggregator
        instances: 2
        stateful: true
        eof_queue: eof_local_bank_max_aggregator
        ready_queue: ready_local_bank_max_aggregator

      - name: bank_resolver
        instances: 1
        stateful: true
        eof_queue: eof_bank_resolver
        ready_queue: ready_bank_resolver