#!/usr/bin/env bash

# Recibe por parámetro el archivo expected y el archivo actual
# Valida que existan
# Les saca el header con tail -n +2, salvo que uses --keep-header
# Ordena ambos archivos con sort
# Compara los archivos ordenados con diff
# Si son iguales, imprime OK
# Si son distintos, guarda las diferencias en comparison_output/diff.txt

set -euo pipefail

EXPECTED_FILE=""
ACTUAL_FILE=""
OUTPUT_DIR="./comparison_output"
SKIP_HEADER=true

show_help() {
  echo "Usage:"
  echo "  ./compare_csv_unordered.sh --expected-file <file> --actual-file <file> [options]"
  echo ""
  echo "Options:"
  echo "  --expected-file   Expected output CSV file"
  echo "  --actual-file     Actual output CSV file generated by the TP"
  echo "  --output-dir      Directory for temporary sorted files. Default: ./comparison_output"
  echo "  --keep-header     Do not skip the first CSV line"
  echo "  -h, --help        Show this help message"
  echo ""
  echo "Example:"
  echo "  ./compare_csv_unordered.sh \\"
  echo "    --expected-file './RULE_1_HI-Medium_Trans.csv' \\"
  echo "    --actual-file './minor_transactions.csv'"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --expected-file)
      EXPECTED_FILE="$2"
      shift 2
      ;;
    --actual-file)
      ACTUAL_FILE="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --keep-header)
      SKIP_HEADER=false
      shift
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      show_help
      exit 1
      ;;
  esac
done

if [[ -z "$EXPECTED_FILE" || -z "$ACTUAL_FILE" ]]; then
  echo "ERROR: --expected-file and --actual-file are required."
  show_help
  exit 1
fi

if [[ ! -f "$EXPECTED_FILE" ]]; then
  echo "ERROR: expected file not found: $EXPECTED_FILE"
  exit 1
fi

if [[ ! -f "$ACTUAL_FILE" ]]; then
  echo "ERROR: actual file not found: $ACTUAL_FILE"
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

EXPECTED_SORTED="$OUTPUT_DIR/expected.sorted.csv"
ACTUAL_SORTED="$OUTPUT_DIR/actual.sorted.csv"
DIFF_FILE="$OUTPUT_DIR/diff.txt"

echo "Sorting files..."

if [[ "$SKIP_HEADER" == true ]]; then
  tail -n +2 "$EXPECTED_FILE" | sort > "$EXPECTED_SORTED"
  tail -n +2 "$ACTUAL_FILE" | sort > "$ACTUAL_SORTED"
else
  sort "$EXPECTED_FILE" > "$EXPECTED_SORTED"
  sort "$ACTUAL_FILE" > "$ACTUAL_SORTED"
fi

echo "Comparing sorted files..."

if diff -u "$EXPECTED_SORTED" "$ACTUAL_SORTED" > "$DIFF_FILE"; then
  echo "OK: files match regardless of row order."
  rm -f "$DIFF_FILE"
  exit 0
else
  echo "ERROR: files are different."
  echo "Diff saved at: $DIFF_FILE"
  echo ""
  echo "First differences:"
  head -n 40 "$DIFF_FILE"
  exit 1
fi